routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\InwardOutwardController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('materials', MaterialController::class);
Route::resource('categories', CategoryController::class);
Route::resource('inwardoutwards', InwardOutwardController::class);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $fillable = ['name'];
}

app/Models/InwardOutward.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class InwardOutward extends Model
{
    use HasFactory;

    protected $fillable = ['material_id', 'date', 'quantity'];

    public function material()
    {
        return $this->belongsTo(Material::class);
    }
}

app/Models/Material.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Material extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = ['name', 'opening_balance', 'category_id'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function inwardOutwards()
    {
        return $this->hasMany(InwardOutward::class);
    }

    public function calculateCurrentBalance()
    {
        $totalInwardQuantity = $this->inwardOutwards()->sum('quantity');
        return $this->opening_balance + $totalInwardQuantity;
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::all();
        return view('categories.index', compact('categories'));
    }

    public function create()
    {
        return view('categories.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
        ]);

        Category::create($request->all());

        return redirect()->route('categories.index')->with('success', 'Category added successfully.');
    }

    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('categories.edit', compact('category'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string',
        ]);

        $category = Category::findOrFail($id);
        $category->update($request->all());

        return redirect()->route('categories.index')->with('success', 'Category updated successfully.');
    }

    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        return redirect()->route('categories.index')->with('success', 'Category deleted successfully.');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/InwardOutwardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\InwardOutward;
use App\Models\Material;

class InwardOutwardController extends Controller
{

    public function index()
    {
        $inwardOutwards = InwardOutward::all();
        return view('inward_outwards.index', compact('inwardOutwards'));
    }

    public function create()
    {
        $materials = Material::all();
        return view('inward_outwards.create', compact('materials'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'material_id' => 'required|exists:materials,id',
            'date' => 'required|date',
            'quantity' => 'required|numeric',
        ]);

        InwardOutward::create($request->all());

        return redirect()->route('inwardoutwards.index')->with('success', 'Inward/Outward Quantity added successfully.');
    }

}

app/Http/Controllers/MaterialController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Material;
use App\Models\Category;

class MaterialController extends Controller
{

    public function index()
    {
        $materials = Material::all();
        return view('materials.index', compact('materials'));
    }

    public function create()
    {
        $categories = Category::all();
        return view('materials.create', compact('categories'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'opening_balance' => 'required|numeric',
            'category_id' => 'required|exists:categories,id',
        ]);

        Material::create($request->all());

        return redirect()->route('materials.index')->with('success', 'Material added successfully.');
    }

    public function edit($id)
    {
        $material = Material::findOrFail($id);
        $categories = Category::all();
        return view('materials.edit', compact('material', 'categories'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string',
            'opening_balance' => 'required|numeric',
            'category_id' => 'required|exists:categories,id',
        ]);

        $material = Material::findOrFail($id);
        $material->update($request->all());

        return redirect()->route('materials.index')->with('success', 'Material updated successfully.');
    }

   public function destroy($id)
    {
        $material = Material::findOrFail($id);
        $material->delete();
        return redirect()->route('materials.index')->with('success', 'Material soft deleted successfully.');
    }

}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Add Category</div>
                        <div class="card-body">
                        <form action="{{ route('categories.store') }}" method="post">
                            @csrf
                            <div class="mb-3">
                                <label for="name" class="form-label">Category Name:</label>
                                <input type="text" name="name" class="form-control" required>
                            </div>

                            <button type="submit" class="btn btn-primary">Save Category</button>
                            <a href="{{ route('categories.index') }}" class="btn btn-secondary">Back to Categories</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit Category</div>
                    <div class="card-body">
                        <form action="{{ route('categories.update', $category->id) }}" method="post">
                            @csrf
                            @method('PATCH')

                            <div class="mb-3">
                                <label for="name" class="form-label">Category Name:</label>
                                <input type="text" name="name" class="form-control" value="{{ $category->name }}" required>
                            </div>

                            <button type="submit" class="btn btn-primary">Update Category</button>
                             <a href="{{ route('categories.index') }}" class="btn btn-secondary">Back to Categories</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1>All Categories</h1>
    <div>
        <a href="{{ route('categories.create') }}" class="btn btn-success">Add Category</a>
    </div>
</div>
    <table class="table table-striped table-bordered zero-configuration">
        <thead>
            <tr>
                <th>Category name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($categories as $category)
                <tr>
                    <td>{{ $category->name }}</td>
                    <td>
                        <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-primary">Edit</a>
                        <form action="{{ route('categories.destroy', $category->id) }}" method="post" class="d-inline">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger ml-2">Delete</button>
                        </form>
                    </td>

                </tr>
            @endforeach
        </tbody>
    </table>
   
@endsection

resources/views/inward_outwards/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Add Inward Outward Quantity</div>
                    <div class="card-body">
                        <form action="{{ route('inwardoutwards.store') }}" method="post">
                            @csrf
                            <div class="mb-3">
                                <label for="material_id" class="form-label">Material:</label>
                                <select name="material_id" class="form-select" required>
                                    @foreach($materials as $material)
                                        <option value="{{ $material->id }}">{{ $material->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="mb-3">
                                <label for="date" class="form-label">Date:</label>
                                <input type="date" name="date" class="form-control" required>
                            </div>

                            <div class="mb-3">
                                <label for="quantity" class="form-label">Quantity:</label>
                                <input type="number" name="quantity" class="form-control" step="0.01" required>
                            </div>

                            <button type="submit" class="btn btn-primary">Save</button>
                             <a href="{{ route('inwardoutwards.index') }}" class="btn btn-secondary">Back to Inward/Outward Quantities</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

   
@endsection

resources/views/inward_outwards/index.blade.php
<!-- resources/views/inwardoutwards/index.blade.php -->

@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1>Add Inward/Outward Quantity</h1>
    <div>
        <a href="{{ route('inwardoutwards.create') }}" class="btn btn-success">Add Inward Outward</a>
    </div>
</div>
    <table class="table table-striped table-bordered zero-configuration">
        <thead>
            <tr>
                <th>Material category</th>
                <th>Material name</th>
                <th>Date</th>
                <th>Quantity</th>
               
            </tr>
        </thead>
        <tbody>
            @foreach($inwardOutwards as $inwardOutward)
                <tr>
                    <td>{{ $inwardOutward->material->category->name }}</td>
                    <td>{{ $inwardOutward->material->name }}</td>
                    <td>{{ $inwardOutward->date }}</td>
                    <td>{{ $inwardOutward->quantity }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
   
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Material Management App</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Include any additional CSS styles if needed -->

    <style>
        /* Custom style for the selected li with bold */
        .navbar-nav .nav-item.active a {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ route('materials.index') }}">Material Management App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item {{ request()->is('materials*') ? 'active' : '' }}">
                            <a class="nav-link" href="{{ route('materials.index') }}">Materials</a>
                        </li>
                        <li class="nav-item {{ request()->is('categories*') ? 'active' : '' }}">
                            <a class="nav-link" href="{{ route('categories.index') }}">Categories</a>
                        </li>
                        <li class="nav-item {{ request()->is('inwardoutwards*') ? 'active' : '' }}">
                            <a class="nav-link" href="{{ route('inwardoutwards.index') }}">Inward/Outward</a>
                        </li>
                        <!-- Add links for other sections as needed -->
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container mt-4">
        @yield('content')
    </main>

    <footer class="mt-4 text-center">
        <!-- Footer content goes here -->
    </footer>

    <!-- Include Bootstrap JS and Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Include any additional JS scripts or external libraries -->
</body>
</html>

resources/views/materials/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Add Material</div>
                    <div class="card-body">
                        <form action="{{ route('materials.store') }}" method="post">
                            @csrf
                            <div class="mb-3">
                                <label for="category_id" class="form-label">Material Category:</label>
                                <select name="category_id" class="form-select" required>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="mb-3">
                                <label for="name" class="form-label">Material Name:</label>
                                <input type="text" name="name" class="form-control" required>
                            </div>

                            <div class="mb-3">
                                <label for="opening_balance" class="form-label">Opening Balance:</label>
                                <input type="number" name="opening_balance" class="form-control" step="0.01" required>
                            </div>

                            <button type="submit" class="btn btn-primary">Save Material</button>
                              <a href="{{ route('materials.index') }}" class="btn btn-secondary">Back to Materials</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
  
@endsection

resources/views/materials/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit Material</div>
                    <div class="card-body">
                        <form action="{{ route('materials.update', $material->id) }}" method="post">
                            @csrf
                            @method('PATCH')

                            <div class="mb-3">
                                <label for="category_id" class="form-label">Material Category:</label>
                                <select name="category_id" class="form-select" required>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}" {{ $material->category_id == $category->id ? 'selected' : '' }}>
                                            {{ $category->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="mb-3">
                                <label for="name" class="form-label">Material Name:</label>
                                <input type="text" name="name" class="form-control" value="{{ $material->name }}" required>
                            </div>

                            <div class="mb-3">
                                <label for="opening_balance" class="form-label">Opening Balance:</label>
                                <input type="number" name="opening_balance" class="form-control" step="0.01" value="{{ $material->opening_balance }}" required>
                            </div>

                            <button type="submit" class="btn btn-primary">Update Material</button>
                               <a href="{{ route('materials.index') }}" class="btn btn-secondary">Back to Materials</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
 
@endsection

resources/views/materials/index.blade.php
@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1>All Materials</h1>
    <div>
        <a href="{{ route('materials.create') }}" class="btn btn-success">Add Material</a>
    </div>
</div>
    <table class="table table-striped table-bordered zero-configuration">
        <thead>
            <tr>
                <th>Material category</th>
                <th>Material name</th>
                <th>Opening balance</th>
                <th>Current balance</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($materials as $material)
                <tr>
                    <td>{{ $material->category->name }}</td>
                    <td>{{ $material->name }}</td>
                    <td>{{ $material->opening_balance }}</td>
                    <td>{{ $material->calculateCurrentBalance() }}</td>
                    <td><a href="{{ route('materials.edit', $material->id) }}" class="btn btn-primary">Edit</a>
                        <form action="{{ route('materials.destroy', $material->id) }}" class="d-inline" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger ml-2">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    
@endsection